// src/PageRoom.tsx
import { map, merge, partition } from "rxjs"
import { FlashCover } from "./FlashCover"
import { Timer } from "./Timer"
import { useObservable } from "./useObservable"
import { useRoom } from "./useRoom"
import { useTimerState } from "./useTimerState"
import { useTitleAsTimeViewer } from "./useTitleAsTimeViewer"
import { createCache } from "./util/createCache"
import { isRoom, Room } from "./zod/roomZod"

export function PageRoom({ roomId }: { roomId: Room["id"] }) {
  const _room$ = useRoom(roomId)
  const [room$, invalid$] = cache(_room$, () => {
    const [room$, _invalid$] = partition(_room$, isRoom)
    const invalid$ = merge(room$.pipe(map(() => null)), _invalid$)

    return [room$, invalid$]
  })

  const invalid = useObservable(invalid$)
  if (invalid) {
    throw invalid
  }

  const timerState$ = useTimerState(roomId)

  useTitleAsTimeViewer(timerState$)

  return (
    <div className="mx-auto h-screen max-w-prose">
      <Timer room$={room$} timerState$={timerState$} className="h-full" />

      <FlashCover timerState$={timerState$} />
    </div>
  )
}

const cache = createCache()

// src/routes/PageRoom.svelte
<script lang="ts">
  import { isRoom, type InvalidDoc, type Room } from "$lib/schema/roomSchema"
  import { fromRoute } from "$lib/toRoute"
  import { useAudio } from "$lib/useAudio"
  import { useRoom } from "$lib/useRoom"
  import { useSetup } from "$lib/useSetup"
  import { useTimerState } from "$lib/useTimerState"
  import { firstValueFrom, map, merge, partition, type Observable } from "rxjs"
  import ConfigArea from "./ConfigArea.svelte"
  import FlashCover from "./FlashCover.svelte"
  import { setSoundCall } from "./setSoundCall"
  import { setTitleAsTimeViewer } from "./setTitleAsTimeViewer"
  import Timer from "./Timer.svelte"
  import { useConfig } from "./useConfig"

  export let roomId: Room["id"]

  $: [room$, invalidRoomId$] = roomOrInvalid(useRoom(roomId))
  $: setup$ = $invalidRoomId$ && useSetup($invalidRoomId$)?.()
  $: timerState$ = useTimerState(roomId)

  let unsubscribeTitle: (() => void) | undefined
  $: {
    unsubscribeTitle?.()
    unsubscribeTitle = setTitleAsTimeViewer(timerState$)
  }

  const config$ = useConfig()
  const audio = useAudio()

  let unsubscribeSound: (() => void) | undefined
  $: {
    unsubscribeSound?.()
    unsubscribeSound = setSoundCall(
      timerState$,
      config$.pipe(map((_) => _.sound === "on")),
      () => {
        console.debug("audio.play()")
        audio.play()
      }
    )
  }

  function roomOrInvalid(_room$: Observable<Room | InvalidDoc>) {
    const [room$, _invalid$] = partition(_room$, isRoom)

    const clearWhenValid$ = room$.pipe(map(() => null))
    const invalidRoomId$ = merge(
      clearWhenValid$,
      _invalid$.pipe(map(([, roomId]) => roomId))
    )

    return [room$, invalidRoomId$] as const
  }
</script>

{#await Promise.all( [setup$, firstValueFrom(room$), firstValueFrom(timerState$)] ) then}
  <div class="mx-auto h-screen max-w-prose">
    <Timer {room$} {timerState$} class="h-full">
      <div slot="header" class="pt-2 text-center">
        <h1 aria-label="タイマーの名前: {$room$.name}">
          {$room$.name}
        </h1>
      </div>

      <ConfigArea
        infoHash="#{fromRoute(['room', roomId])}"
        class="flex items-center justify-evenly px-6"
      />
    </Timer>

    <FlashCover {timerState$} />
  </div>
{/await}
