// src/Timer.tsx
import clsx from "clsx"
import { serverTimestamp } from "firebase/firestore"
import { useRef } from "react"
import { Observable } from "rxjs"
import { CircleButton } from "./CircleButton"
import { DurationSelect } from "./DurationSelect"
import { icon } from "./icon"
import { setHash } from "./observeHash"
import { getItem } from "./storage"
import { TimerState } from "./timerReducer"
import { TimeViewer } from "./TimeViewer"
import { TransparentButton } from "./TransparentButton"
import { useMediaPermission } from "./useAudio"
import { toggleConfig, useConfig } from "./useConfig"
import { useDispatch } from "./useDispatch"
import { useObservable } from "./useObservable"
import { Room } from "./zod/roomZod"

export function Timer({
  room$,
  timerState$,
  className,
}: {
  room$: Observable<Room>
  timerState$: Observable<TimerState>
  className?: string
}) {
  const { id: roomId, name: roomName, lockedBy } = useObservable(room$)
  const locked = lockedBy && lockedBy !== getItem("userId")

  const state = useObservable(timerState$)

  const [pending, dispatch] = useDispatch(roomId)

  const durationSelect$ = useRef({
    value: state.initialDuration,
  })
  const primaryButton$ = useRef<HTMLButtonElement>(null)

  return (
    <>
      <div className={clsx("grid grid-rows-[auto_5fr_auto_4fr]", className)}>
        <div className="pt-2 text-center">
          <h1>{roomName}</h1>
        </div>

        <form
          className="contents"
          onSubmit={async (e) => {
            e.preventDefault()

            if (state.mode !== "editing") return

            dispatch({
              type: "start",
              withDuration: durationSelect$.current.value,
              at: serverTimestamp(),
            })

            primaryButton$.current?.focus()
          }}
        >
          <div className="grid place-items-center tabular-nums">
            {!locked && state.mode === "editing" ? (
              <DurationSelect
                key={state.mode + state.initialDuration}
                innerRef={durationSelect$}
                defaultValue={state.initialDuration}
              />
            ) : (
              <TimeViewer
                timerState$={timerState$}
                scale={window.devicePixelRatio}
              />
            )}
          </div>

          {locked ? (
            <div className="flex items-center justify-around">
              <CircleButton disabled className="text-2xl">
                {icon("lock-outline")}
              </CircleButton>

              <CircleButton
                disabled
                className="text-2xl"
                color={state.mode === "running" ? "orange" : "green"}
              >
                {icon("lock-outline")}
              </CircleButton>
            </div>
          ) : (
            <div className="flex items-center justify-around">
              <CircleButton
                disabled={state.mode === "editing"}
                className="text-xs"
                onClick={() => {
                  dispatch({
                    type: "cancel",
                  })
                }}
              >
                キャンセル
              </CircleButton>

              {state.mode === "editing" ? (
                <CircleButton
                  innerRef={primaryButton$}
                  color="green"
                  type="submit"
                >
                  開始
                </CircleButton>
              ) : state.mode === "running" ? (
                <CircleButton
                  innerRef={primaryButton$}
                  color="orange"
                  onClick={() => {
                    dispatch({
                      type: "pause",
                      at: serverTimestamp(),
                    })
                  }}
                >
                  一時停止
                </CircleButton>
              ) : (
                <CircleButton
                  innerRef={primaryButton$}
                  color="green"
                  onClick={() => {
                    if (pending) return

                    dispatch({
                      type: "resume",
                      at: serverTimestamp(),
                    })
                  }}
                >
                  再開
                </CircleButton>
              )}
            </div>
          )}
        </form>

        <ConfigArea
          className="flex items-center justify-evenly px-6"
          onInfoClick={() => {
            setHash(["info", roomId])
          }}
        />
      </div>
    </>
  )
}

function ConfigArea({
  className,
  onInfoClick,
}: {
  className?: string
  onInfoClick?(): void
}) {
  const config = useObservable(useConfig())
  const permission = useObservable(useMediaPermission(), "denied")

  return (
    <div className={className}>
      <TransparentButton
        title="フラッシュを切り替える"
        className="h-12 w-12 text-2xl"
        onClick={() => {
          toggleConfig("flash")
        }}
      >
        {config.flash === "on" ? icon("flash") : icon("flash-off")}
      </TransparentButton>

      <TransparentButton
        title="音を切り替える"
        className="h-12 w-12 text-2xl"
        onClick={() => {
          if (permission === "denied") return

          toggleConfig("sound")
        }}
      >
        {config.sound === "on" && permission === "canplay"
          ? icon("volume-high")
          : icon("volume-off")}
      </TransparentButton>

      <TransparentButton
        title="情報を開く"
        className="h-12 w-12 text-2xl"
        onClick={onInfoClick}
      >
        {icon("information")}
      </TransparentButton>
    </div>
  )
}

// src/routes/Timer.svelte
<script lang="ts">
  import DurationSelect from "$lib/DurationSelect.svelte"
  import Icon from "$lib/Icon.svelte"
  import TimeViewer from "$lib/TimeViewer.svelte"
  import { getId } from "$lib/util/getId"
  import { humanReadableLabelOf } from "$lib/util/humanReadableLabelOf"
  import clsx from "clsx"
  import { distinctUntilChanged, map, type Observable } from "rxjs"
  import type { HTMLButtonAttributes } from "svelte/elements"
  import { now } from "../now"
  import type { Room } from "../schema/roomSchema"
  import type { TimerState } from "../schema/timerReducer"
  import { serverTimestamp } from "../serverTimestamp"
  import { useDispatch } from "../useDispatch"

  export let room$: Observable<Room>
  export let timerState$: Observable<TimerState>
  export { className as class }
  let className: string = ""

  const _id = getId()
  const id = (_: "timer" | "status") => _id + _

  $: state = $timerState$
  $: ({ id: roomId } = $room$)

  $: initialDuration$ = timerState$.pipe(
    map((_) => _.initialDuration),
    distinctUntilChanged()
  )
  $: duration = $initialDuration$

  const locked = false
  $: [pending, dispatch] = useDispatch(roomId)

  let button: {
    label: string
    onClick?: HTMLButtonAttributes["on:click"]
    attr: HTMLButtonAttributes
  }
  $: {
    switch (state.mode) {
      case "editing": {
        button = {
          label: "開始",
          attr: {
            type: "submit",
            class: clsx("circle-button circle-button-green"),
          },
        }
        break
      }

      case "running": {
        button = {
          label: "一時停止",
          onClick: () => {
            dispatch({
              type: "pause",
              at: serverTimestamp,
            })
          },
          attr: {
            type: "button",
            class: clsx("circle-button circle-button-orange"),
          },
        }
        break
      }

      case "paused": {
        button = {
          label: "再開",
          onClick: () => {
            if (pending) return

            dispatch({
              type: "resume",
              at: serverTimestamp,
            })
          },
          attr: {
            type: "button",
            class: clsx("circle-button circle-button-green"),
          },
        }
        break
      }
    }
  }

  const onSubmit = () => {
    if (state.mode !== "editing") return

    dispatch({
      type: "start",
      withDuration: duration,
      at: serverTimestamp,
    })
  }

  const onCancel = async () => {
    await dispatch({
      type: "cancel",
    })
  }
</script>

<div class={clsx("grid grid-rows-[auto_5fr_auto_4fr]", className)}>
  <slot name="header"><div /></slot>

  <form
    aria-label="タイマーの値を設定"
    class="contents"
    on:submit|preventDefault={onSubmit}
  >
    <p id={id("status")} role="status" class="sr-only">
      {#if state.mode === "editing"}
        {`タイマーは編集中、値は${humanReadableLabelOf(state.initialDuration)}`}
      {:else if state.mode === "running"}
        {`タイマーは実行中、残り${humanReadableLabelOf(
          state.restDuration - (now() - state.startedAt)
        )}`}
      {:else if state.mode === "paused"}
        {`タイマーは一時停止中、残り${humanReadableLabelOf(
          state.restDuration
        )}`}
      {/if}
    </p>

    <div id={id("timer")} class="relative grid place-items-center tabular-nums">
      {#if !locked && state.mode === "editing"}
        <div
          class="grid aspect-video w-[512px] max-w-[100vw] touch-pinch-zoom place-items-center"
        >
          {#key $initialDuration$}
            <DurationSelect bind:value={duration} />
          {/key}
        </div>
      {:else}
        <div class="absolute">
          <TimeViewer {timerState$} />
        </div>
      {/if}
    </div>

    <h2 class="sr-only">タイマーの操作</h2>

    <div class="flex items-center justify-around">
      {#if locked}
        <button
          aria-controls="{id('status')} {id('timer')}"
          type="button"
          disabled
          class="circle-button circle-button-gray text-2xl"
        >
          <Icon name="lock-outline" />
        </button>

        <button
          aria-controls="{id('status')} {id('timer')}"
          type="button"
          disabled
          class={clsx(
            "circle-button text-2xl",
            state.mode === "running"
              ? "circle-button-orange"
              : "circle-button-green"
          )}
        >
          <Icon name="lock-outline" />
        </button>
      {:else}
        <button
          aria-controls="{id('status')} {id('timer')}"
          type="button"
          disabled={state.mode === "editing"}
          class="circle-button circle-button-gray text-xs"
          on:click={onCancel}
        >
          キャンセル
        </button>

        <button {...button.attr} on:click={button.onClick}>
          {button.label}
        </button>
      {/if}
    </div>
  </form>

  <slot />
</div>
