// src/PageRoom.svelte
<script lang="ts">
  import { map, merge, partition, type Observable } from "rxjs"
  import Timer from "./Timer.svelte"
  import { useRoom } from "./useRoom"
  import { useSetup } from "./useSetup"
  import { useTimerState } from "./useTimerState"
  import { isRoom, type InvalidDoc, type Room } from "./zod/roomZod"

  function roomOrInvalid(_room$: Observable<Room | InvalidDoc>) {
    const [room$, _invalid$] = partition(_room$, isRoom)
    const invalid$ = merge(room$.pipe(map(() => null)), _invalid$)

    return [room$, invalid$] as const
  }

  function getSetup(invalid: InvalidDoc) {
    const [, invalidRoomId] = invalid
    return useSetup(invalidRoomId)
  }

  export let roomId: Room["id"]

  $: [room$, invalid$] = roomOrInvalid(useRoom(roomId))
  $: setup = $invalid$ && getSetup($invalid$)
  $: timerState$ = useTimerState(roomId)
</script>

{#await setup?.() then}
  <div class="mx-auto h-screen max-w-prose">
    <Timer {room$} {timerState$} class="h-full" />
  </div>
{/await}

// src/PageRoom.tsx
import { map, merge, partition } from "rxjs"
import { FlashCover } from "./FlashCover"
import { Timer } from "./Timer"
import { useObservable } from "./useObservable"
import { useRoom } from "./useRoom"
import { useTimerState } from "./useTimerState"
import { useTitleAsTimeViewer } from "./useTitleAsTimeViewer"
import { createCache } from "./util/createCache"
import { isRoom, Room } from "./zod/roomZod"

export function PageRoom({ roomId }: { roomId: Room["id"] }) {
  const _room$ = useRoom(roomId)
  const [room$, invalid$] = cache(_room$, () => {
    const [room$, _invalid$] = partition(_room$, isRoom)
    const invalid$ = merge(room$.pipe(map(() => null)), _invalid$)

    return [room$, invalid$]
  })

  const invalid = useObservable(invalid$)
  if (invalid) {
    throw invalid
  }

  const timerState$ = useTimerState(roomId)

  useTitleAsTimeViewer(timerState$)

  return (
    <div className="mx-auto h-screen max-w-prose">
      <Timer room$={room$} timerState$={timerState$} className="h-full" />

      <FlashCover timerState$={timerState$} />
    </div>
  )
}

const cache = createCache()
