// src/Timer.tsx
import clsx from "clsx"
import { serverTimestamp } from "firebase/firestore"
import { useRef } from "react"
import { Observable } from "rxjs"
import { CircleButton } from "./CircleButton"
import { DurationSelect } from "./DurationSelect"
import { icon } from "./icon"
import { setHash } from "./observeHash"
import { getItem } from "./storage"
import { TimerState } from "./timerReducer"
import { TimeViewer } from "./TimeViewer"
import { TransparentButton } from "./TransparentButton"
import { useMediaPermission } from "./useAudio"
import { toggleConfig, useConfig } from "./useConfig"
import { useDispatch } from "./useDispatch"
import { useObservable } from "./useObservable"
import { Room } from "./zod/roomZod"

export function Timer({
  room$,
  timerState$,
  className,
}: {
  room$: Observable<Room>
  timerState$: Observable<TimerState>
  className?: string
}) {
  const { id: roomId, name: roomName, lockedBy } = useObservable(room$)
  const locked = lockedBy && lockedBy !== getItem("userId")

  const state = useObservable(timerState$)

  const [pending, dispatch] = useDispatch(roomId)

  const durationSelect$ = useRef({
    value: state.initialDuration,
  })
  const primaryButton$ = useRef<HTMLButtonElement>(null)

  return (
    <>
      <div className={clsx("grid grid-rows-[auto_5fr_auto_4fr]", className)}>
        <div className="pt-2 text-center">
          <h1>{roomName}</h1>
        </div>

        <form
          className="contents"
          onSubmit={async (e) => {
            e.preventDefault()

            if (state.mode !== "editing") return

            dispatch({
              type: "start",
              withDuration: durationSelect$.current.value,
              at: serverTimestamp(),
            })

            primaryButton$.current?.focus()
          }}
        >
          <div className="grid place-items-center tabular-nums">
            {!locked && state.mode === "editing" ? (
              <DurationSelect
                key={state.mode + state.initialDuration}
                innerRef={durationSelect$}
                defaultValue={state.initialDuration}
              />
            ) : (
              <TimeViewer
                timerState$={timerState$}
                scale={window.devicePixelRatio}
              />
            )}
          </div>

          {locked ? (
            <div className="flex items-center justify-around">
              <CircleButton disabled className="text-2xl">
                {icon("lock-outline")}
              </CircleButton>

              <CircleButton
                disabled
                className="text-2xl"
                color={state.mode === "running" ? "orange" : "green"}
              >
                {icon("lock-outline")}
              </CircleButton>
            </div>
          ) : (
            <div className="flex items-center justify-around">
              <CircleButton
                disabled={state.mode === "editing"}
                className="text-xs"
                onClick={() => {
                  dispatch({
                    type: "cancel",
                  })
                }}
              >
                キャンセル
              </CircleButton>

              {state.mode === "editing" ? (
                <CircleButton
                  innerRef={primaryButton$}
                  color="green"
                  type="submit"
                >
                  開始
                </CircleButton>
              ) : state.mode === "running" ? (
                <CircleButton
                  innerRef={primaryButton$}
                  color="orange"
                  onClick={() => {
                    dispatch({
                      type: "pause",
                      at: serverTimestamp(),
                    })
                  }}
                >
                  一時停止
                </CircleButton>
              ) : (
                <CircleButton
                  innerRef={primaryButton$}
                  color="green"
                  onClick={() => {
                    if (pending) return

                    dispatch({
                      type: "resume",
                      at: serverTimestamp(),
                    })
                  }}
                >
                  再開
                </CircleButton>
              )}
            </div>
          )}
        </form>

        <ConfigArea
          className="flex items-center justify-evenly px-6"
          onInfoClick={() => {
            setHash(["info", roomId])
          }}
        />
      </div>
    </>
  )
}

function ConfigArea({
  className,
  onInfoClick,
}: {
  className?: string
  onInfoClick?(): void
}) {
  const config = useObservable(useConfig())
  const permission = useObservable(useMediaPermission(), "denied")

  return (
    <div className={className}>
      <TransparentButton
        title="フラッシュを切り替える"
        className="h-12 w-12 text-2xl"
        onClick={() => {
          toggleConfig("flash")
        }}
      >
        {config.flash === "on" ? icon("flash") : icon("flash-off")}
      </TransparentButton>

      <TransparentButton
        title="音を切り替える"
        className="h-12 w-12 text-2xl"
        onClick={() => {
          if (permission === "denied") return

          toggleConfig("sound")
        }}
      >
        {config.sound === "on" && permission === "canplay"
          ? icon("volume-high")
          : icon("volume-off")}
      </TransparentButton>

      <TransparentButton
        title="情報を開く"
        className="h-12 w-12 text-2xl"
        onClick={onInfoClick}
      >
        {icon("information")}
      </TransparentButton>
    </div>
  )
}

// src/Timer.svelte
<script lang="ts">
  import clsx from "clsx"
  import { map, type Observable } from "rxjs"
  import DurationSelect from "./DurationSelect.svelte"
  import Icon from "./Icon.svelte"
  import { now } from "./now"
  import { getItem } from "./storage"
  import type { TimerState } from "./timerReducer"
  import TimeViewer from "./TimeViewer.svelte"
  import { useDispatch } from "./useDispatch"
  import { getId } from "./util/getId"
  import { humanReadableLabelOf } from "./util/humanReadableLabelOf"
  import { ServerTimestamp } from "./util/ServerTimestamp"
  import type { Room } from "./zod/roomZod"

  export let room$: Observable<Room>
  export let timerState$: Observable<TimerState>

  let className: string = ""
  export { className as class }

  const _id = getId()
  const id = (_: "timer" | "status") => _id + _

  $: ({ id: roomId, name: roomName, lockedBy } = $room$ ?? {})
  $: locked = lockedBy && lockedBy !== getItem("userId")

  $: [pending, dispatch] = useDispatch(roomId)

  $: label$ = timerState$.pipe(
    map((state) => {
      switch (state.mode) {
        case "editing": {
          return `タイマーは編集中です。値は${humanReadableLabelOf(
            state.initialDuration
          )}`
        }

        case "running": {
          return `タイマーは実行中です。残り${humanReadableLabelOf(
            state.restDuration - (now() - state.startedAt)
          )}`
        }

        case "paused": {
          return `タイマーは一時停止中です。残り${humanReadableLabelOf(
            state.restDuration
          )}`
        }
      }
    })
  )

  let duration: number
  let prev: number
  $: {
    const current = $timerState$?.initialDuration
    if (current !== prev) {
      duration = current
    }

    prev = current
  }
</script>

{#if $timerState$}
  {@const state = $timerState$}

  <div class={clsx("grid grid-rows-[auto_5fr_auto_4fr]", className)}>
    <div class="pt-2 text-center">
      <h1 aria-label="タイマーの名前: {roomName}">
        {roomName}
      </h1>
    </div>

    <form
      class="contents"
      on:submit|preventDefault={() => {
        if (state.mode !== "editing") return

        dispatch({
          type: "start",
          withDuration: duration,
          at: new ServerTimestamp(now()),
        })
      }}
    >
      <p id={id("status")} role="status" class="sr-only">
        {$label$}
      </p>

      <div id={id("timer")} class="grid place-items-center tabular-nums">
        {#if !locked && state.mode === "editing"}
          <div
            class="grid aspect-video w-[512px] max-w-[100vw] touch-pinch-zoom place-items-center"
          >
            <DurationSelect bind:value={duration} />
          </div>
        {:else}
          <TimeViewer {timerState$} />
        {/if}
      </div>

      {#if locked}
        <div class="flex items-center justify-around">
          <button
            aria-controls="{id('status')} {id('timer')}"
            type="button"
            disabled
            class="circle-button circle-button-gray text-2xl"
          >
            <Icon name="lock-outline" />
          </button>

          <button
            aria-controls="{id('status')} {id('timer')}"
            type="button"
            disabled
            class="circle-button circle-button-green text-2xl"
            class:!circle-button-orange={state.mode === "running"}
          >
            <Icon name="lock-outline" />
          </button>
        </div>
      {:else}
        <div class="flex items-center justify-around">
          <button
            aria-controls="{id('status')} {id('timer')}"
            type="button"
            disabled={state.mode === "editing"}
            class="circle-button circle-button-gray text-xs"
            on:click={() => {
              dispatch({
                type: "cancel",
              })
            }}
          >
            キャンセル
          </button>

          {#if state.mode === "editing"}
            <button
              aria-controls="{id('status')} {id('timer')}"
              type="submit"
              class="circle-button circle-button-green"
            >
              開始
            </button>
          {:else if state.mode === "running"}
            <button
              aria-controls="{id('status')} {id('timer')}"
              type="button"
              class="circle-button circle-button-orange"
              on:click={() => {
                dispatch({
                  type: "pause",
                  at: new ServerTimestamp(now()),
                })
              }}
            >
              一時停止
            </button>
          {:else}
            <button
              aria-controls="{id('status')} {id('timer')}"
              type="button"
              class="circle-button circle-button-green"
              on:click={() => {
                if (pending) return

                dispatch({
                  type: "resume",
                  at: new ServerTimestamp(now()),
                })
              }}
            >
              再開
            </button>
          {/if}
        </div>
      {/if}
    </form>
  </div>
{/if}
